swagger: "2.0"
info:
  version: "1.0.0"
  title: MyLocale web app endpoints(Jinja templates)
tags:
- name: "users"
  description: "User related functions"
- name: "profiles"
  description: "Profile functions"
- name: "groups"
  description: "Group functions"
- name: "posts"
  description: "Post functions"
paths:
    /web/registration/:
      get:
        tags:
        - "users"
        summary: "User registration page"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
      post:
        tags:
        - "users"
        summary: "Register new users"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: username
            type: string
            description: New username
          - in: formData
            name: password
            type: string
            description: Password
          - in: formData
            name: confirm password
            type: string
            description: Confirm Password
        responses:
          "200":
            description: "User registration successful"
          "302":
            description: "Redirect depending on outcome"
    /web/login/:
      get:
        tags:
        - "users"
        summary: "User login page"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
      post:
        tags:
        - "users"
        summary: "Login users"
        consumes:
        - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: username
            type: string
            description: Username
          - in: formData
            name: password
            type: string
            description: Password
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
    /web/logout/:
      get:
        tags:
        - "users"
        summary: "Logs out currently logged in user session"
        responses:
          "200":
            description: "successful operation"
    /web/profile/:
      get:
        tags:
        - "profiles"
        summary: "Show profile page"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
    /web/profile/profilename/:
      get:
        tags:
        - "profiles"
        summary: "Add profile name"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect to profile page"
      post:
        tags:
        - "profiles"
        summary: "Create/update profile name"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: name
            type: string
            description: New profile name
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
    /web/profile/uploadimage/:
      post:
        tags:
          - "profiles"
        summary: "uploads profile picture"
        consumes:
        - "multipart/form-data"
        parameters:
          - name: "file"
            in: "formData"
            description: "file to upload"
            required: true
            type: "file"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
    /web/profile/deleteimage/:
      post:
        tags:
          - "profiles"
        summary: "delete profile picture"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect to profile page"
    /web/profile/locationsearch/:
      get:
        tags:
        - "profiles"
        summary: "Show location search page"
        responses:
          "200":
            description: "successful operation"
          "404":
            description: "page not found"
      post:
        tags:
        - "profiles"
        summary: "Search location for according to postcode"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: postcode
            type: integer
            description: Postcode
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Reload page with location data"
          "404":
            description: "Location not found"
    /web/profile/addlocation/:
      post:
        tags:
        - "profiles"
        summary: "Add profile location"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: postcode
            type: integer
            description: Postcode
          - in: formData
            name: suburb
            type: string
            description: Suburb
          - in: formData
            name: state
            type: string
            description: State
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect profile page"
    /groups/:
      get:
        tags:
        - "groups"
        summary: "Get groups"
        responses:
          "200":
            description: "successful operation"
    /groups/recommendations/:
      get:
        tags:
        - "groups"
        summary: "Get group recommendations"
        responses:
          "200":
            description: "successful operation"
    /groups/{group_id}:
      get:
        tags:
        - "groups"
        summary: "View group by id"
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
        responses:
          "200":
            description: "successful operation"
    /groups/create:
      get:
        tags:
        - "groups"
        summary: "Create group"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to create page"
      post:
        tags:
        - "groups"
        summary: "Create group"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: name
            type: string
            description: New group name
          - in: formData
            name: description
            type: string
            description: Group description
          - in: formData
            name: location
            type: string
            description: Group location
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to view page"
    /groups/{group_id}/update/:
      get:
        tags:
        - "groups"
        summary: "Update group"
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to view page"
      post:
        tags:
        - "groups"
        summary: "Update group"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: name
            type: string
            description: New group name
          - in: formData
            name: description
            type: string
            description: Group description
          - in: formData
            name: location
            type: string
            description: Group location
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to view page"
    /groups/{group_id}/delete/:
      post:
        tags:
        - "groups"
        summary: "Delete group"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: Delete
            type: string
            description: Delete button
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to view page"
    /groups/{group_id}/join/:
      post:
        tags:
        - "groups"
        summary: "Join group"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: Join
            type: string
            description: Join button
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to view page"
    /groups/{group_id}/unjoin/:
     post:
      tags:
      - "groups"
      summary: "Unjoin group"
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: "group_id"
          in: "path"
          required: true
          type: "integer"
        - name: "profile_id"
          in: "query"
          description: "Profile_id for profile search"
          required: true
          type: "integer"
        - in: formData
          name: Unjoin
          type: string
          description: Unjoin button
      responses:
        "200":
          description: "successful operation"
        "302":
          description: "Redirect depending on outcome"
        "401":
          description: "Unauthorised to view page"
    /groups/search/:
      get:
        tags:
        - "groups"
        summary: "Search group"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
      post:
        tags:
        - "groups"
        summary: "Search group"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - in: formData
            name: search keyword
            type: string
            description: Search keyword
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
    /posts/{group_id}:
      get:
        tags:
        - "posts"
        summary: "Get group posts"
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
        responses:
          "200":
            description: "successful operation"
    /posts/{group_id}/create/:
      get:
        tags:
        - "posts"
        summary: "Create post"
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
        responses:
          "200":
            description: "successful operation"
      post:
        tags:
        - "posts"
        summary: "Create post"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "group_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: post
            type: string
            description: New post
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to create post"
    /posts/{post_id}/comment/:
      get:
        tags:
        - "posts"
        summary: "View comments"
        parameters:
          - name: "post_id"
            in: "path"
            required: true
            type: "integer"
        responses:
          "200":
            description: "successful operation"
      post:
        tags:
        - "posts"
        summary: "Comment on post"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "post_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: comment
            type: string
            description: Comment
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to comment"
    /posts/{post_id}/update/:
      get:
        tags:
        - "posts"
        summary: "Update post"
        parameters:
          - name: "post_id"
            in: "path"
            required: true
            type: "integer"
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to update"
      post:
        tags:
        - "posts"
        summary: "Update post"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "post_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: post
            type: string
            description: Updated post
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to update"
    /posts/{post_id}/remove/:
      post:
        tags:
        - "posts"
        summary: "Delete post"
        consumes:
          - application/x-www-form-urlencoded
        parameters:
          - name: "post_id"
            in: "path"
            required: true
            type: "integer"
          - in: formData
            name: Delete
            type: string
            description: Delete button
        responses:
          "200":
            description: "successful operation"
          "302":
            description: "Redirect depending on outcome"
          "401":
            description: "Unauthorised to delete post"